window.onload=function(){
	var projectObject=[
		{
			"link":"index1.html",
			"linkName":"轮播实例，checkbox实例，日期实例"
		},
		{
			"link":"1pxBorderDemo.html",
			"linkName":"1px边线实例"
		},
		{
			"link":"calendar.html",
			"linkName":"日历实例"
		},
		{
			"link":"dragNav.html",
			"linkName":"可拖动菜单实例"
		},
		{
			"link":"dropLoadMore.html",
			"linkName":"下拉加载更多实例"
		},
		{
			"link":"fontAnimation.html",
			"linkName":"字体图标库实例"
		},
		{
			"link":"formDemo.html",
			"linkName":"美化表单实例"
		},
		{
			"link":"guaguale.html",
			"linkName":"刮刮乐实例"
		},
		{
			"link":"imageLazyLoad.html",
			"linkName":"图片懒加载实例"
		},
		{
			"link":"layoutDemo.html",
			"linkName":"常用布局实例"
		},
		{
			"link":"loadingSy.html",
			"linkName":"加载动画实例"
		},
		{
			"link":"login.html",
			"linkName":"登录页面实例"
		},
		{
			"link":"lottery.html",
			"linkName":"抽奖实例"
		},
		{
			"link":"moveDirection.html",
			"linkName":"手势移动方向判断实例"
		},
		{
			"link":"pageScroll.html",
			"linkName":"上下翻页实例"
		},
		{
			"link":"popModal.html",
			"linkName":"自定义弹窗实例"
		},
		{
			"link":"popModalPlugin.html",
			"linkName":"弹窗插件实例"
		},
		{
			"link":"posFixed.html",
			"linkName":"fix位置兼容解决方案实例"
		},
		{
			"link":"rotateMenu.html",
			"linkName":"旋转菜单实例"
		},
		{
			"link":"scrollFixed.html",
			"linkName":"向下滑动固定导航实例"
		},
		{
			"link":"shakeDemo.html",
			"linkName":"摇一摇实例"
		},
		{
			"link":"shili1.html",
			"linkName":"事件点透解析实例"
		},
		{
			"link":"shili2.html",
			"linkName":"防止误触实例"
		},
		{
			"link":"shili3.html",
			"linkName":"点击实例"
		},
		{
			"link":"sideBarLocate.html",
			"linkName":"侧边栏字母定位实例"
		},
		{
			"link":"sideBarMove.html",
			"linkName":"侧边栏滑动实例"
		},
		{
			"link":"starGrade.html",
			"linkName":"星星评分实例"
		},
		{
			"link":"swipeLeft.html",
			"linkName":"列表项左滑实例"
		},
		{
			"link":"tabDemo.html",
			"linkName":"tab切换实例"
		},
		{
			"link":"touchDemo.html",
			"linkName":"touch实例"
		},
		{
			"link":"yzm.html",
			"linkName":"验证码实例"
		}
	];
	
	new Vue({
		el:'#navUl',
		data:{
			items:projectObject
		}
	});
}